### ISSUE TITLE
could Synergy fit on a floppy?

### ISSUE THREAD

**Issue by informer2016** [JackScottAU/Synergy-OS#1]
Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command its possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry! Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_

**Comment by JackScottAU** [comment]
Thanks for submitting this issue. At the moment Synergy OS only targets (virtual) CD-ROM in the form of ISO images, and I don't believe the future is in floppy disks. Most testing is done via virtual machine, where it's trivial to update an ISO or hard disk image. So I can't see any value in this.

**Comment by informer2016** [comment]
@JackScottAU There's still a practical use for floppies today, but only as their "virtual images" - to easily put them inside open source BIOS and boot from there! I can't use other formats _(e.g. tiny hdd img or iso)_ - not supported :smile: It's equally easy to test the floppies with a virtual machine: in VirtualBox, I just added a virtual floppy controller in the settings of virtual machine - and then it could be used the same way as a virtual CDROM; in QEMU it's also easy, "-fda" flag in console
